version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: superlongpassword
      MYSQL_USER: api_manager
      MYSQL_PASSWORD: StrongPassword123!
    volumes:
      - ./ini.sql:/docker-entrypoint-initdb.d/ini.sql
      - ./ini2.sql:/docker-entrypoint-initdb.d/ini2.sql
    networks:
      - backend-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend-net
    ports:
      - "5555:5555"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - backend-net
    ports:
      - "3000:3000"  # Expose Next.js on port 3000
    depends_on:
      - mysql
      - backend

networks:
  backend-net:
    driver: bridge